Выполнение задания 19
GolovkoStepan/simple_rack_app pull request #1
Opened 2020-11-07 13:44 UTC by GolovkoStepan

2020-11-08 13:30 UTC, VidgarVii commented on application.rb
> +  DEFAULT_HEADERS = { 'Content-Type' => 'text/plain' }.freeze
можно использовать дефолтную настройку для Content-Type
В рамках этой задачи это может быть приемлемо

use Rack::ContentType, "text/plain"

2020-11-08 13:30 UTC, VidgarVii commented on application.rb
> +  TARGET_ROUTE    = '/time'
вот смотри. Я часто общаюсь с клиентом. И понял 2 вещи.
1 Клиент всегда захочет что-то еще
2 Клиент сам не знает что он хочет
(особенно это офигенно расписано в книге Дяди Боба Идеальный программист)
И если придет задача например добавить еще 1 ендпойнт. Тебе придется переписывать почти весь класс.
Как минимум для роутов я бы использовал табличный метод. Это мега упростит жизнь
Привет.
ROUTES = { '/time' => TimeParser }.freeze

2020-11-08 13:30 UTC, VidgarVii commented on application.rb
> +      ok(response_headers, [time_parser.time.to_s])
У тебя для реквеста используется Rack::Request это хорошо. А почему обделил Rack::Response для создания ответа? Он будет грустить(

2020-11-08 13:30 UTC, VidgarVii commented on application.rb
> +      raise InvalidQueryFormat, "Unknown time format: #{time_parser.invalid_types}" if time_parser.invalid_types?
сложно читабельная конструкция. 
Guard clause хорошо использовать в начале блока как начальное условие.
Используй сигнатуру 
if
else
end

2020-11-08 13:30 UTC, VidgarVii commented on application.rb
> +      raise InvalidQueryFormat, "Unknown time format: #{time_parser.invalid_types}" if time_parser.invalid_types?
В продолжении темы про переписывание всего приложения при изменении или добавлении функционала. 
Обрати внимания что данный метод является всего лишь делегатом запроса. Выполняет запрос классТаймПарсер. Т.е. это уже получается реализация паттерна Контроллер. Обязательно почитай про паттерны GRASP. По факту он не должен заморачиваться знаниями интерфейса этого ТаймПарсера. 
Было бы хорошо его структурировать в какую нить единую для всех случаев форму.
Типо так. Но у тебя может своя реализация
```
result = ROUTES[...].call(body: request.params)
if result.success?
  respons body
else
  response error
end
```
Конечно когда у тебя этих контроллеров мб тьма как рельсах и для роутов выделена целая отдельная абстракция со своим дсл. то там ты можешь быть более красноречивым.

2020-11-08 13:30 UTC, VidgarVii commented on application.rb
> +  end
то что ты умеешь пользоваться эксепшенами это прекрасно. Но еще лучше когда их нет. Не стоит строить логику на выбрасывания ошибок.  Одна из причин, они жутко медленные. Какой то stop the world происходит когда выбрасывается ошибка.

2020-11-08 13:30 UTC, VidgarVii commented on lib/time_parser.rb
> +  end
предикат на предикат. Не очень. invalid_types.any? и так не плохо и декларативно выглядет. Но это уже вкусовщина

2020-11-08 13:30 UTC, VidgarVii commented on lib/time_parser.rb
> +    Time.now.strftime(FORMAT_TYPES.values_at(*@types).join('-')) if @types.any? && @invalid_types.empty?
types.any? а для него у тебя нет отдельного метода =(  А тут аж @invalid_types.empty?
Надо придерживаться единообразия.

2020-11-08 13:30 UTC, VidgarVii commented on lib/time_parser.rb
> +    @types         = query_str&.split(',') || []
если query_str нил. Всё что ниже написано не имеет смысла. Можно сразу возвращать ответ.

2020-11-08 13:30 UTC, VidgarVii commented on lib/time_parser.rb
> +    Time.now.strftime(FORMAT_TYPES.values_at(*@types).join('-')) if @types.any? && @invalid_types.empty?
А вот этот не понятный код `FORMAT_TYPES.values_at(*@types).join('-') `я бы абстрагировал в метод с понятным именем

2020-11-08 13:30 UTC, VidgarVii commented on lib/time_parser.rb
> +end
В классе забыл про инкапсуляцию. А про модификаторы доступа

2020-11-08 13:30 UTC, VidgarVii commented on application.rb
> +      raise ResourceNotFound, "Resource not found: #{request.path_info}" unless request.path_info == TARGET_ROUTE
начиная писать код с перечисления возможных ошибок попахивает GOLANG. После него руки мыть хочется. Хотя инструмент крутой. Мы же за читаемость кода. Прочитал 3 строчки кода, а я еще не понял, что вообще тут происходит. Конечно можешь сказать, что я леньтяй и читать не люблю. Но мне кажется все кодеры такие

2020-11-08 14:59 UTC, GolovkoStepan commented on application.rb
> +  DEFAULT_HEADERS = { 'Content-Type' => 'text/plain' }.freeze
Не знал, спс. Но кмк мой подход как-то лучше смотрится, с учетом того, что дефолтные хедеры могут еще появиться, и тогда они все будут в одном месте. Не придется бегать по коду в догадках откуда берется этот Content-Type

2020-11-08 15:02 UTC, GolovkoStepan commented on application.rb
> +  TARGET_ROUTE    = '/time'
Можно сделать, да. Можно роуты и в отдельном файле хранить. Но по тз роут один, и я на 148% уверен, что новых не будет. Получается упрощение ради упрощения

2020-11-08 15:05 UTC, GolovkoStepan commented on application.rb
> +      ok(response_headers, [time_parser.time.to_s])
Какое преимущество мне это даст?

2020-11-08 15:07 UTC, GolovkoStepan commented on application.rb
> +  DEFAULT_HEADERS = { 'Content-Type' => 'text/plain' }.freeze
После моего следующего коммента этот мой будет лишен смысла, поэтому исправлю)

2020-11-08 15:11 UTC, GolovkoStepan commented on application.rb
> +      raise InvalidQueryFormat, "Unknown time format: #{time_parser.invalid_types}" if time_parser.invalid_types?
Не совсем понял. Я не пытался как то делегировать обработку запроса классу TimeParser. У этого класса одна единственная обязанность: принять определенную строку, дать возможность мне получить инфу, могу ли я но основе этой строки получить Time. Больше ничего мне от него не надо.

2020-11-08 15:14 UTC, GolovkoStepan commented on application.rb
> +  end
Ну, не знаю. Не вижу ничего криминального в использовании ексепшенов, тем более когда они используются по своему назначению. То, что они медленные - ну, наверно да. Так или иначе, они везде используются.

2020-11-08 15:14 UTC, GolovkoStepan commented on lib/time_parser.rb
> +  end
Согласен)

2020-11-08 15:16 UTC, GolovkoStepan commented on lib/time_parser.rb
> +    Time.now.strftime(FORMAT_TYPES.values_at(*@types).join('-')) if @types.any? && @invalid_types.empty?
1 коммент: Шутку оценил)
2 коммент: А что уж в этом коде непонятного? Ну ладно, вынесу в отдельный метод

2020-11-08 15:20 UTC, GolovkoStepan commented on lib/time_parser.rb
> +    @types         = query_str&.split(',') || []
Какой ответ? Ответ на http запрос? Выше я писал, что TimeParser не настолько крутой, чтобы еще и этим управлять. Его задача предельна проста. Класс должен переваривать данные, которые в него идут и давать мне понять что я могу получить в итоге.
Вообще, надо бы запретить передачу nil в конструктор. Все же, иногда так не хватает строгой типизации

2020-11-08 15:24 UTC, GolovkoStepan commented on lib/time_parser.rb
> +end
Ну а чего уж тут нужно инкапсулировать? Тут 2 метода всего. И то один я удалю. Класс простой как 3 копейки.

2020-11-08 15:26 UTC, GolovkoStepan commented on lib/time_parser.rb
> +end
А, забыл, аргумент функции strftime это же теперь будет целый метод! Тогда да, пожалуй, путь он будет приватным =)

2020-11-08 15:31 UTC, GolovkoStepan commented on application.rb
> +      raise ResourceNotFound, "Resource not found: #{request.path_info}" unless request.path_info == TARGET_ROUTE
Не понимаю чего тут такого? Обработка ошибок в отдельном методе. Так как у нас переход на левый url по тз запрещен, то я считаю, что это исключительная ситуация, и сразу бросаю ексепшен. Идем далее - если форматы левые, то это тоже исключительная ситуация. Бросаем ексепшен. Если мы таки дошли до #ok, то все - отдаем респонс, берем пирожок с полки и отдыхаем.

2020-11-08 16:21 UTC, VidgarVii commented on application.rb
> +      ok(response_headers, [time_parser.time.to_s])
соблюдение ООП и принципов SOLID. И использование готового решения приводит к меньшей поддержке кода. Тем более ты уже используешь Rack. Зачем писать свой велосипед, если инструмент у тебя уже под рукой.

2020-11-08 16:24 UTC, VidgarVii commented on application.rb
> +      raise InvalidQueryFormat, "Unknown time format: #{time_parser.invalid_types}" if time_parser.invalid_types?
метод call в классе Application сам ни чего не парсит и время не получает. Для этого у тебя есть специальная АТД TimeParser. И Application использует TimeParser для получения данных. Это и есть делегирование задачи. На этом всё ООП держится. Отправка сообщения 5-ая парадигма.

2020-11-08 16:25 UTC, VidgarVii commented on application.rb
> +  end
не аргумент

2020-11-08 16:32 UTC, VidgarVii commented on lib/time_parser.rb
> +    @types         = query_str&.split(',') || []
на счёт нил согласен. Но жизнь боль. И undefined method for NinClass будет сниться ночами. Так чтобы не выполнять лишнюю работу, так как она не имеет смысла, следует засунуть guard clause наверх в конструктор для валидации параметра. Или raise если ты их так любишь. Он тут будет уместен.
Об этом говориться в основах оптимизации кода и еще можно встретить книгах про рекурсии. Будет еще..

2020-11-08 16:35 UTC, VidgarVii commented on lib/time_parser.rb
> +end
Это хорошо что он простой. Но интерфейсы ни кто не отменял. Это нормально если у этого класса будут сразу обращаться к time или invalid_types? Я думаю это вспомогательные методы. При проектировании надо отталкиваться от противного. Всё под запретом, а затем открываешь то что нужно.

2020-11-08 16:37 UTC, VidgarVii commented on application.rb
> +  TARGET_ROUTE    = '/time'
код чище и проще будет.

2020-11-08 16:38 UTC, GolovkoStepan commented on application.rb
> +      ok(response_headers, [time_parser.time.to_s])
Этот велосипед всего лишь массив, элементами которого являются число, хеш и массив. Как раз то, что и будет передано в конструктор Rack::Response. Круто, что это есть, да и солид норм тема. Но явного преимущества я не увидел, мне проще вернуть массив.

2020-11-08 16:39 UTC, GolovkoStepan commented on application.rb
> +      raise InvalidQueryFormat, "Unknown time format: #{time_parser.invalid_types}" if time_parser.invalid_types?
Ну я не спорю, однако у нас нет 100500 роутов, имея которые стоило бы сделать так. Есть один роут - его и обрабатываем. Я сделал так, потому что ТЗ такое. Оно не поменяется. Смысла в данном улучшении, в данной ситуации, нет.

2020-11-08 16:47 UTC, GolovkoStepan commented on application.rb
> +  TARGET_ROUTE    = '/time'
Я дико извиняюсь, но я не могу понять, каким образом данное изменение придаст коду чистоту и простоту, если мы имеем всего 1 роут и это количество никогда не изменится

2020-11-08 16:47 UTC, VidgarVii commented on application.rb
> +  end
обработку ошибок придумали на для построения бизнес логики. То что пользователь зашел не на тут урл это ошибка пользователя. А твоё приложение должно уметь такой кейс обрабатывать. И для твоего приложения вернуть 404 или другой статус не будет ошибкой.

2020-11-08 16:47 UTC, VidgarVii commented on application.rb
> +  end
https://github.com/rubocop-hq/ruby-style-guide#no-exceptional-flows

2020-11-08 16:48 UTC, GolovkoStepan commented on application.rb
> +  end
Ну ладно ¯\_(ツ)_/¯

2020-11-08 16:54 UTC, GolovkoStepan commented on lib/time_parser.rb
> +end
Сейчас есть всего 1 метод time, который вернет или Time или nil, в зависимости от того, есть ли паленые форматы. Я действительно не понимаю, что тут нужно инкапсулировать. Если, конечно, речь идет не о методе public_time, который вызовет private_time, условно говоря.

2020-11-08 16:57 UTC, GolovkoStepan commented on application.rb
> +  end
Исключения — это конструкция языка позволяющая управлять потоком выполнения. Это конструкция, стоящая в одном ряду с if, for и return. И всё. Этот механизм ничем более не является. Только управление потоком.

2020-11-08 16:57 UTC, VidgarVii commented on application.rb
> +      raise InvalidQueryFormat, "Unknown time format: #{time_parser.invalid_types}" if time_parser.invalid_types?
тут ошибка проектирования, а не плохая постановка ТЗ. Да выполнять задачу надо в рамках поставленного ТЗ. Но более важно, что твой код был поддерживаем и маштабируемый. Опять же СОЛИД (ОСР) и жизненный геморой. 
У тебя есть ядро Application. Его задача:
1 принять запрос
2 найти раба для исполнения задачи (это намёк на шаблонный метод)
3 получить от него ответ
4 отдать ответ реку.
ВСЁ. А у тебя часть бизнес логики размазана м/у TimeParser и Application . Т.е. когда я открывают код в Application я вижу кучу эксепшенов и парсинг даты. SRP - каждый чувак должен заниматься ТОЛЬКО своей работай.

2020-11-08 17:01 UTC, VidgarVii requested changes

2020-11-08 17:01 UTC, VidgarVii commented on application.rb
> +  end
они все и семантически разные операторы и задачи выполняют разные. О каком ряде вообще идёт речь?

2020-11-08 17:05 UTC, VidgarVii requested changes

2020-11-08 17:05 UTC, VidgarVii commented on lib/time_parser.rb
> +end
Так всё у тебя уже стоит private до formatted_time_str. Так что тут норм. Или я что-то профокапил... Это всё Application виноват =)

2020-11-08 17:14 UTC, GolovkoStepan commented on application.rb
> +  end
Я к тому, что не просто так же придумали 2 примерно одинаковых штуки, таки как Exception и Error. Если говорить о руби. И exception вроде как раз для обработки исключительных ситуаций. Что и делается у меня)

2020-11-08 17:18 UTC, GolovkoStepan commented on lib/time_parser.rb
> +    @types         = query_str&.split(',') || []
Ну те мне надо просто убрать Safe Navigation Operator, проверять в начале конструктора агрумент на нил, если нил - то даем @types и @invalid_types пустые массивы и return.

2020-11-08 17:23 UTC, GolovkoStepan commented on application.rb
> +      raise InvalidQueryFormat, "Unknown time format: #{time_parser.invalid_types}" if time_parser.invalid_types?
SRP тут соблюдается, time_parser занят своей работой со строками, application своей - он там вроде как какой то env принимает и массив возвращает. Или я не прав?)

2020-11-08 20:13 UTC, VidgarVii commented on application.rb
> +  end
https://github.com/rubocop-hq/ruby-style-guide#no-exceptional-flows

2020-11-08 20:14 UTC, VidgarVii commented on application.rb
> +  end
техническую и семантическую причину я уже отписал выше

2020-11-08 20:24 UTC, VidgarVii commented on application.rb
> +      raise InvalidQueryFormat, "Unknown time format: #{time_parser.invalid_types}" if time_parser.invalid_types?
Да time_parser занят своим делом. Но Ядро твоего приложения это Application. И при проектирование парсера ты должен учитывать этот Application с учетом возможностей масштабирования проекта. Ты думаешь о том как выполнить этот ТЗ. Написать тупо рабочую прогу. Хороший разработчик найдет 10ки способ выполнить это простое задание. Но оставит только то, которое будет читабельное,  поддерживаемое, масштабируемое и пр. Это требует бизнес. По этому бородатые старые дядьки на придумали 10ки идиом и договорились как писать код, чтобы не спиться после каждой хотелки клиента.

2020-11-08 20:48 UTC, VidgarVii commented on application.rb
> +      ok(response_headers, [time_parser.time.to_s])
А для чего тогда ты использовал Rack::Request? Все данные и так хранятся в env и про них уже знает класс Application. Лишний класс TimeParser тоже не нужен. По факту нам важен только класс Time который и так вшит в ruby. Да и на самом деле можно и без него время узнать. Модули тоже в топку. Кто их вообще придумал? Оставим только raise, а весь код напишем в методе call. И это будет работать даже лучше чем со всеми этими странными парадигмами ООП. Которая почти каждая опровергается как 2 пальца. Но мир не так работает. Он ппц сложный. И люди до сих пор бьют голову как эта вся хрень сущесвтует. ООП по сути мега упрощенная модель нашего мира. Всё декомпозированно. Все сущности живут отдельно и мало знают про огромный окружающий мир. Но мир как то существует. Потому что каждый занимается своим делом. И знает только то, что ему положено. И старые пердуны вроде Алана Кея это поняли. И дали нам ООП и кучу мозговыносящих идей. Да это сложно и сразу не понятно. И Ruby это ООП язык. И чтобы работать над чем-то большим и сложным надо учитывать кучу факторов. И код писать так, что потом после тебя будет над ним работать маньяк, который знает где ты живешь. А не так чтобы тупо работало по ТЗ.

2020-11-08 20:51 UTC, VidgarVii commented on application.rb
> +  TARGET_ROUTE    = '/time'
это абсолютно не важно изменится там что-то или нет. Но твой код всегда должен быть готов к новым приключениям без вазелина

2020-11-08 20:53 UTC, VidgarVii commented on lib/time_parser.rb
> +    @types         = query_str&.split(',') || []
нууу..... неа

2020-11-09 05:11 UTC, GolovkoStepan commented on application.rb
> +      ok(response_headers, [time_parser.time.to_s])
Rack::Request я использовал потому что там есть метод path_info для получения.
Rack::Response я не использовал потому что там нет ничего нужного для меня.
Вот и все)

2020-11-09 05:21 UTC, GolovkoStepan commented on application.rb
> +      raise InvalidQueryFormat, "Unknown time format: #{time_parser.invalid_types}" if time_parser.invalid_types?
Причем тут бизнес? Это просто лаба по программированию, прям как в универе. Этот проект никто не будет дальше дорабатывать, расширять и тп. Я сделал ее самым простым способом, без учета возможных "новых требований" потому что их не будет. Вот такой я плохой разраб, мне не хочется делать лишнюю работу которая никогда не будет использоваться.

2020-11-09 05:30 UTC, GolovkoStepan commented on application.rb
> +  TARGET_ROUTE    = '/time'
Ну давайте тогда добавим поддержку роутов с параметрами, типа /time/:format/show
Давайте еще и вьюхи сделаем, html напишем, ну вообще полный марафет наведем, мало ли что там заказчик скажет) Мы кстати не готовы к большому rps, давайте все на ерланге перепишем, а то мб заказчик скажет что это надо.

2020-11-09 05:49 UTC, VidgarVii commented on application.rb
> +  TARGET_ROUTE    = '/time'
вот когда скажет надо. тогда сделаешь. А пока лишнее. Есть внутренние и внешние стандарты кода и их надо придерживаться. Сейчас я вижу код, который придется допиливать при малейших изменениях функционала. Это плохо. Хотя осталось тебе сделать какую то мелочь

2020-11-11 19:12 UTC, merged